# Dashboards need to be specified here to be created on TestGrid
# A prow annotation will be invalid if it references a dashboard that doesn't exist
dashboards:
- name: googleoss-gcp-guest
- name: googleoss-test-infra
- name: googleoss-esp-v2

dashboard_groups:
  - name: googleoss
    dashboard_names:
    - googleoss-gcp-guest
    - googleoss-test-infra

