apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: image-updater@k8s-testgrid.iam.gserviceaccount.com
  name: testgrid-pusher
  namespace: test-pods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: deployer@k8s-testgrid.iam.gserviceaccount.com
  name: testgrid-deployer
  namespace: test-pods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: testgrid-config-updater@oss-prow.iam.gserviceaccount.com
  name: testgrid-config-updater
  namespace: test-pods
