apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: prow-deployer@oss-prow.iam.gserviceaccount.com
  name: prow-deployer
  namespace: test-pods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: kubernetes-external-secrets-sa@oss-prow.iam.gserviceaccount.com
  name: kubernetes-external-secrets-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: prowjob-default-sa@oss-prow.iam.gserviceaccount.com
  name: prowjob-default-sa
  namespace: test-pods
---
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    iam.gke.io/gcp-service-account: gencred-refresher@oss-prow.iam.gserviceaccount.com
  name: gencred-refresher
  namespace: test-pods
---
