presubmits:
  GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp:
  - name: prow-e2e-tests
    cluster: build-secretmanager-csi
    decorate: true           # Decorate with Prow utilities
    always_run: true         # Run for every PR, or only when requested.
    spec:
      serviceAccountName: prow-test-sa
      containers:
      - image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
        command:
        - test/infra/prow/presubmit.sh

periodics:
- name: prow-e2e-tests-periodic
  cluster: build-secretmanager-csi
  cron: '0 9 * * *' # Run once a day at 9am.
  decorate: true
  annotations:
    testgrid-dashboards: googleoss-secrets-store-csi-driver-provider-gcp
    testgrid-tab-name: periodic
    description: "Runs E2E tests on the main branch continuously."
  extra_refs: # Run test against main branch.
  - org: GoogleCloudPlatform
    repo: secrets-store-csi-driver-provider-gcp
    base_ref: main  
  spec:
    serviceAccountName: prow-test-sa
    containers:
    - image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
      command:
      - test/infra/prow/presubmit.sh
      env:
        - name: GKE_VERSION
          value: "RAPID"
        - name: GCP_PROVIDER_SHA
          value: main
