presubmits:
  GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp:
  - name: prow-e2e-tests
    cluster: build-secretmanager-csi
    decorate: true           # Decorate with Prow utilities
    always_run: true         # Run for every PR, or only when requested.
    spec:
      containers:
      - image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
        command:
        - test/infra/prow/presubmit.sh
