presubmits:
  GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp:
  - name: prow-e2e-tests
    cluster: build-secretmanager-csi
    decorate: true           # Decorate with Prow utilities
    always_run: true         # Run for every PR, or only when requested.
    spec:
      containers:
      - image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
        command:
        - test/infra/prow/presubmit.sh
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcs-access-service-account/service-account.json
        volumeMounts:
        - name: gcs-access-service-account
          mountPath: /etc/gcs-access-service-account
      volumes:
        - name: gcs-access-service-account
          secret:
            secretName: service-account
