postsubmits:
  GoogleCloudPlatform/osconfig:
  - name: osconfig-build
    cluster: gcp-guest
    decorate: true
    annotations:
      testgrid-dashboards: google-gcp-guest
    spec:
      containers:
      - image: gcr.io/gcp-guest/daisy-builder:latest
        command:
        - "/main.sh"
        args: ["gcp-guest", "us-west1-a", "deb9,el6,el7,el8,goo", "gs://gcp-guest-packages/osconfig/"]
        volumeMounts:
        - name: daisy-service-account
          mountPath: /etc/daisy-service-account
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/daisy-service-account/creds.json
      volumes:
      - name: daisy-service-account
        secret:
          secretName: daisy-service-account
    max_concurrency: 10
    branches:
    - ^master$
  GoogleCloudPlatform/guest-oslogin:
  - name: oslogin-build
    cluster: gcp-guest
    decorate: true
    annotations:
      testgrid-dashboards: google-gcp-guest
    spec:
      containers:
      - image: gcr.io/gcp-guest/daisy-builder:latest
        command:
        - "/main.sh"
        args: ["gcp-guest", "us-west1-a", "./packaging/build_packages_wf.json", "gs://gcp-guest-packages/oslogin/"]
        volumeMounts:
        - name: daisy-service-account
          mountPath: /etc/daisy-service-account
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/daisy-service-account/creds.json
      volumes:
      - name: daisy-service-account
        secret:
          secretName: daisy-service-account
    max_concurrency: 10
    branches:
    - ^master$
  GoogleCloudPlatform/guest-configs:
  - name: guest-config-build
    cluster: gcp-guest
    decorate: true
    annotations:
      testgrid-dashboards: google-gcp-guest
    spec:
      containers:
      - image: gcr.io/gcp-guest/daisy-builder:latest
        command:
        - "/main.sh"
        args: ["gcp-guest", "us-west1-a", "./packaging/build_packages_wf.json", "gs://gcp-guest-packages/guest-configs/"]
        volumeMounts:
        - name: daisy-service-account
          mountPath: /etc/daisy-service-account
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/daisy-service-account/creds.json
      volumes:
      - name: daisy-service-account
        secret:
          secretName: daisy-service-account
    max_concurrency: 10
    branches:
    - ^master$
  GoogleCloudPlatform/guest-agent:
  - name: guest-agent-build
    cluster: gcp-guest
    decorate: true
    annotations:
      testgrid-dashboards: google-gcp-guest
    spec:
      containers:
      - image: gcr.io/gcp-guest/daisy-builder:latest
        command:
        - "/main.sh"
        args: ["gcp-guest", "us-west1-a", "./packaging/build_packages_wf.json", "gs://gcp-guest-packages/guest-agent/"]
        volumeMounts:
        - name: daisy-service-account
          mountPath: /etc/daisy-service-account
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/daisy-service-account/creds.json
      volumes:
      - name: daisy-service-account
        secret:
          secretName: daisy-service-account
    max_concurrency: 10
    branches:
    - ^master$

presubmits:
  GoogleCloudPlatform/osconfig:
  - name: osconfig-presubmit-build
    cluster: gcp-guest
    run_if_changed: ".*/packaging/.*"
    trigger: "(?m)^/packagebuild$"
    rerun_command: "/packagebuild"
    context: prow/presubmit/packagebuild
    extra_refs:
    - org: GoogleCloudPlatform
      repo: guest-test-infra
      base_ref: master
      workdir: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/daisy-builder:latest
        command:
        - "/main.sh"
        args: ["gcp-guest", "us-west1-a", "deb9,el6,el7,el8,goo"]
        volumeMounts:
        - name: daisy-service-account
          mountPath: /etc/daisy-service-account
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/daisy-service-account/creds.json
      volumes:
      - name: daisy-service-account
        secret:
          secretName: daisy-service-account
  - name: osconfig-presubmit-gocheck
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gocheck$"
    rerun_command: "/gocheck"
    context: prow/presubmit/gocheck
    decorate: true
    annotations:
      testgrid-dashboards: google-gcp-guest
      testgrid-tab-name: "OSConfig presubmits - gocheck"
    spec:
      containers:
      - image: gcr.io/gcp-guest/gocheck:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: osconfig-presubmit-gobuild
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gobuild$"
    rerun_command: "/gobuild"
    context: prow/presubmit/gobuild
    decorate: true
    annotations:
      testgrid-dashboards: google-gcp-guest
      testgrid-tab-name: "OSConfig presubmits - gobuild"
    spec:
      containers:
      - image: gcr.io/gcp-guest/gobuild:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: osconfig-presubmit-gotest
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gotest$"
    rerun_command: "/gotest"
    context: prow/presubmit/gotest
    decorate: true
    annotations:
      testgrid-dashboards: google-gcp-guest
      testgrid-tab-name: "OSConfig presubmits - gotest"
    spec:
      containers:
      - image: gcr.io/gcp-guest/gotest:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
        volumeMounts:
        - name: codecov
          mountPath: /etc/codecov
          readOnly: true
      volumes:
      - name: codecov
        secret:
          secretName: codecov

  GoogleCloudPlatform/guest-agent:
  - name: guest-agent-presubmit-gocheck
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gocheck$"
    rerun_command: "/gocheck"
    context: prow/presubmit/gocheck
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gocheck:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: guest-agent-presubmit-gobuild
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gobuild$"
    rerun_command: "/gobuild"
    context: prow/presubmit/gobuild
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gobuild:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: guest-agent-presubmit-gotest
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gotest$"
    rerun_command: "/gotest"
    context: prow/presubmit/gotest
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gotest:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
        volumeMounts:
        - name: codecov
          mountPath: /etc/codecov
          readOnly: true
      volumes:
      - name: codecov
        secret:
          secretName: codecov
  - name: guest-agent-presubmit-build
    cluster: gcp-guest
    run_if_changed: ".*/packaging/.*"
    trigger: "(?m)^/packagebuild$"
    rerun_command: "/packagebuild"
    context: prow/presubmit/packagebuild
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/daisy-builder:latest
        command:
        - "/main.sh"
        args: ["gcp-guest", "us-west1-a", "./packaging/build_packages_wf.json"]
        volumeMounts:
        - name: daisy-service-account
          mountPath: /etc/daisy-service-account
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/daisy-service-account/creds.json
      volumes:
      - name: daisy-service-account
        secret:
          secretName: daisy-service-account

  GoogleCloudPlatform/guest-logging-go:
  - name: guest-logging-presubmit-gocheck
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gocheck$"
    rerun_command: "/gocheck"
    context: prow/presubmit/gocheck
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gocheck:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: guest-logging-presubmit-gobuild
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gobuild$"
    rerun_command: "/gobuild"
    context: prow/presubmit/gobuild
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gobuild:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: guest-logging-presubmit-gotest
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gotest$"
    rerun_command: "/gotest"
    context: prow/presubmit/gotest
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gotest:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
        volumeMounts:
        - name: codecov
          mountPath: /etc/codecov
          readOnly: true
      volumes:
      - name: codecov
        secret:
          secretName: codecov

  GoogleCloudPlatform/guest-oslogin:
  - name: oslogin-presubmit-build
    cluster: gcp-guest
    run_if_changed: ".*/packaging/.*"
    trigger: "(?m)^/packagebuild$"
    rerun_command: "/packagebuild"
    context: prow/presubmit/packagebuild
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/daisy-builder:latest
        command:
        - "/main.sh"
        args: ["gcp-guest", "us-west1-a", "./packaging/build_packages_wf.json"]
        volumeMounts:
        - name: daisy-service-account
          mountPath: /etc/daisy-service-account
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/daisy-service-account/creds.json
      volumes:
      - name: daisy-service-account
        secret:
          secretName: daisy-service-account
  - name: oslogin-presubmit-selinux-module
    cluster: gcp-guest
    run_if_changed: ".*/policy/.*"
    trigger: "(?m)^/modcheck$"
    rerun_command: "/modcheck"
    context: prow/presubmit/selinux_module_check
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/selinux-tools:latest
        imagePullPolicy: Always
        command:
        - "./selinux/validate.sh"
  - name: oslogin-presubmit-make-prowbuild
    cluster: gcp-guest
    always_run: true
    trigger: "(?m)^/build$"
    rerun_command: "/build"
    context: prow/presubmit/build
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/build-essential:latest
        imagePullPolicy: Always
        command:
        - make
        args:
        - prowbuild
  - name: oslogin-presubmit-test
    cluster: gcp-guest
    always_run: true
    trigger: "(?m)^/test$"
    rerun_command: "/test"
    context: prow/presubmit/test
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/build-essential:latest
        imagePullPolicy: Always
        command:
        - make
        args:
        - prowtest

  GoogleCloudPlatform/guest-configs:
  - name: guest-configs-presubmit-build
    cluster: gcp-guest
    run_if_changed: ".*/packaging/.*"
    trigger: "(?m)^/packagebuild$"
    rerun_command: "/packagebuild"
    context: prow/presubmit/packagebuild
    extra_refs:
    - org: GoogleCloudPlatform
      repo: guest-test-infra
      base_ref: master
      workdir: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/daisy-builder:latest
        command:
        - "/main.sh"
        args: ["gcp-guest", "us-west1-a", "./packaging/build_packages_wf.json"]
        volumeMounts:
        - name: daisy-service-account
          mountPath: /etc/daisy-service-account
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/daisy-service-account/creds.json
      volumes:
      - name: daisy-service-account
        secret:
          secretName: daisy-service-account

  GoogleCloudPlatform/guest-test-infra:
  - name: infra-presubmit-gocheck
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gocheck$"
    rerun_command: "/gocheck"
    context: prow/presubmit/gocheck
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gocheck:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: infra-presubmit-gobuild
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gobuild$"
    rerun_command: "/gobuild"
    context: prow/presubmit/gobuild
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gobuild:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: infra-presubmit-gotest
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gotest$"
    rerun_command: "/gotest"
    context: prow/presubmit/gotest
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gotest:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
        volumeMounts:
        - name: codecov
          mountPath: /etc/codecov
          readOnly: true
      volumes:
      - name: codecov
        secret:
          secretName: codecov
