postsubmits:
  GoogleCloudPlatform/osconfig:
  - name: osconfig-agent-build
    cluster: gcp-guest
    decorate: true
    spec:
      containers:
        - image: gcr.io/compute-image-tools-test/osconfig-agent-build:latest
          command:
            - "./main.sh"
          volumeMounts:
            - name: compute-image-tools-test-service-account
              mountPath: /etc/compute-image-tools-test-service-account
              readOnly: true
        volumes:
          - name: compute-image-tools-test-service-account
            secret:
              secretName: compute-image-tools-test-service-account
    max_concurrency: 10
    branches:
      - ^master$

presubmits:
  GoogleCloudPlatform/osconfig:
  - name: osconfig-presubmit-gocheck
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gocheck$"
    rerun_command: "/gocheck"
    context: prow/presubmit/gocheck
    decorate: true
    spec:
      containers:
      - image: gcr.io/compute-image-tools-test/gocheck-liam:latest
        command:
        - "/go/main.sh"
        volumeMounts:
        - name: compute-image-tools-test-service-account
          mountPath: /etc/compute-image-tools-test-service-account
          readOnly: true
      volumes:
      - name: compute-image-tools-test-service-account
        secret:
          secretName: compute-image-tools-test-service-account
  - name: osconfig-presubmit-gobuild
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gobuild$"
    rerun_command: "/gobuild"
    context: prow/presubmit/gobuild
    decorate: true
    spec:
      containers:
      - image: gcr.io/compute-image-tools-test/gobuild-liam:latest
        command:
        - "/go/main.sh"
        volumeMounts:
        - name: compute-image-tools-test-service-account
          mountPath: /etc/compute-image-tools-test-service-account
          readOnly: true
      volumes:
      - name: compute-image-tools-test-service-account
        secret:
          secretName: compute-image-tools-test-service-account
  - name: osconfig-presubmit-unittests
    cluster: gcp-guest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/unittests$"
    rerun_command: "/unittests"
    context: prow/presubmit/unittests
    decorate: true
    spec:
      containers:
      - image: gcr.io/compute-image-tools-test/unittests-liam:latest
        command:
        - "/go/main.sh"
        volumeMounts:
        - name: compute-image-tools-test-service-account
          mountPath: /etc/compute-image-tools-test-service-account
          readOnly: true
        - name: codecov
          mountPath: /etc/codecov
          readOnly: true
      volumes:
      - name: compute-image-tools-test-service-account
        secret:
          secretName: compute-image-tools-test-service-account
      - name: codecov
        secret:
          secretName: codecov

periodics:
- name: cluster-gcp-guest
  cluster: gcp-guest
  interval: 30m
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
