---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: prow-monitoring
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - name: http
    port: 3001
    targetPort: http
  - name: nginx
    port: 80
    targetPort: nginx
  selector:
    app: grafana
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: oss-prow-monitoring-knative-dev
  namespace: prow-monitoring
spec:
  domains:
  - oss-prow-monitoring.knative.dev
