# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file contains Kubernetes YAML files for the most important prow
# components. Don't edit resources in this file. Instead, pull them out into
# their own files.
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prowjobs.prow.k8s.io
  # namespace: not-namespaced
spec:
  group: prow.k8s.io
  version: v1
  names:
    kind: ProwJob
    singular: prowjob
    plural: prowjobs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            max_concurrency:
              type: integer
              minimum: 0
            type:
              type: string
              enum:
              - "presubmit"
              - "postsubmit"
              - "periodic"
              - "batch"
        status:
          properties:
            state:
              type: string
              enum:
              - "triggered"
              - "pending"
              - "success"
              - "failure"
              - "aborted"
              - "error"
          anyOf:
          - not:
              properties:
                state:
                  type: string
                  enum:
                  - "success"
                  - "failure"
                  - "error"
          - required:
            - completionTime
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: horologium
  namespace: default
  labels:
    app: horologium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: horologium
  template:
    metadata:
      labels:
        app: horologium
    spec:
      serviceAccountName: horologium
      terminationGracePeriodSeconds: 30
      containers:
      - name: horologium
        image: gcr.io/k8s-prow/horologium:v20200921-becd8c9356
        args:
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --dry-run=false
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: oss-prow-knative-dev
  namespace: default
spec:
  domains:
  - oss-prow.knative.dev
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deck-ing
  namespace: default
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "oss-prow"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/tls-acme: "true"
    networking.gke.io/managed-certificates: oss-prow-knative-dev
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: deck
          servicePort: 80
      - path: /hook
        backend:
          serviceName: hook
          servicePort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerrit
  namespace: default
  labels:
    app: gerrit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerrit
  template:
    metadata:
      labels:
        app: gerrit
    spec:
      serviceAccountName: gerrit
      terminationGracePeriodSeconds: 30
      containers:
      - name: gerrit
        image: gcr.io/k8s-prow/gerrit:v20200921-becd8c9356
        args:
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --cookiefile=/etc/cookies/cookies
        - --gerrit-projects=https://kunit-review.googlesource.com=linux
        - --last-sync-fallback=gs://oss-prow/last-gerrit-sync
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        - name: cookies
          mountPath: /etc/cookies
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
      - name: cookies
        secret:
          defaultMode: 420
          secretName: http-cookiefile
### Cluster rbac rules
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: horologium
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: horologium
  namespace: default
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - create
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: horologium
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "horologium"
subjects:
- kind: ServiceAccount
  name: "horologium"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "iam.gke.io/gcp-service-account": "oss-prow@oss-prow.iam.gserviceaccount.com"
  name: gerrit
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gerrit
  namespace: default
rules:
- apiGroups:
    - "prow.k8s.io"
  resources:
    - prowjobs
  verbs:
    - create
    - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gerrit
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "gerrit"
subjects:
- kind: ServiceAccount
  name: "gerrit"
