apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: private-deck-oauth2-config
  namespace: default
spec:
  backendType: gcpSecretsManager
  projectId: oss-prow
  data:
  - key: oss-prow-private-github-oauth-config
    name: secret
    version: latest
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: private-deck-oauth2
  namespace: default
spec:
  backendType: gcpSecretsManager
  projectId: oss-prow
  data:
  - key: oss-prow-private-github-oauth2-secret
    name: clientID
    version: latest
    property: clientID
  - key: oss-prow-private-github-oauth2-secret
    name: clientSecret
    version: latest
    property: clientSecret
  - key: oss-prow-private-github-oauth2-secret
    name: cookieSecret
    version: latest
    property: cookieSecret
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: prow-monitoring
spec:
  backendType: gcpSecretsManager
  projectId: oss-prow
  data:
  - key: oss-prow__prow-monitoring__grafana
    name: password
    version: latest
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: kubeconfig-build-looker-private
  namespace: default
spec:
  backendType: gcpSecretsManager
  projectId: prow-build-looker-github
  data:
  - key: prow_build_cluster_kubeconfig_build-looker-private
    name: kubeconfig
    version: latest
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: kubeconfig-build-elcarro
  namespace: default
spec:
  backendType: gcpSecretsManager
  projectId: prow-build-graybox
  data:
  - key: prow_build_cluster_kubeconfig_build-elcarro
    name: kubeconfig
    version: latest
