apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub
  namespace: default
  labels:
    app: sub
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sub
  template:
    metadata:
      labels:
        app: sub
    spec:
      terminationGracePeriodSeconds: 120
      serviceAccountName: sub
      containers:
      - name: sub
        image: gcr.io/k8s-prow/sub:v20210920-bd8073b837
        args:
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --grace-period=110s
        - --github-token-path=/etc/github/oauth
        - --dry-run=false
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        resources:
          # The node has 7.91CPU in total, set requests and limits,
          # so that only 2 sub pods are on the same node, and they
          # don't use more than that
          requests:
            cpu: 3
          limits:
            cpu: 3
      volumes:
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
      - name: oauth
        secret:
          secretName: oauth-token-2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sub
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: prow-pubsub@oss-prow.iam.gserviceaccount.com
---
apiVersion: v1
kind: Service
metadata:
  name: sub
  namespace: default
spec:
  selector:
    app: sub
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "sub"
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - create
      - get
      - list
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "sub"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "sub"
subjects:
- kind: ServiceAccount
  name: "sub"
