# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

plank:
  job_url_prefix: https://gubernator.k8s.io/build/
  pod_pending_timeout: 60m
  default_decoration_config:
    timeout: 7200000000000 # 2h
    grace_period: 15000000000 # 15s
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190228-49ac9d2"
      initupload: "gcr.io/k8s-prow/initupload:v20190228-49ac9d2"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190228-49ac9d2"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190228-49ac9d2"
    gcs_configuration:
      bucket: "oss-prow"
      path_strategy: "explicit"
    gcs_credentials_secret: "service-account"

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 24h

prowjob_namespace: default
pod_namespace: test-pods
log_level: info

presubmits:
  https://kunit-review.googlesource.com/linux:
  - name: kunit-test-presubmit
    branches:
    - kunit/alpha/master
    decorate: true
    always_run: true
    spec:
      volumes:
      - name: shared-mem
        emptyDir: {}
      containers:
      - image: gcr.io/kunit-presubmit/kunit
        securityContext:
          privileged: true
        command:
        - /kunit.sh
        volumeMounts:
        - name: shared-mem
          mountPath: /dev/shm

  GoogleCloudPlatform/oss-test-infra:
  - name: pull-prow-config-validate
    branches:
    - master
    decorate: true
    always_run: true
    extra_refs:
    - org: kubernetes
      repo: test-infra
      base_ref: master
      path_alias: k8s.io/test-infra
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190329-811f7954b-master
        command:
        - runner.sh 
        args:
        - bash
        - -c
        - >-
          cd /home/prow/go/src/k8s.io/test-infra &&
          bazel run prow/cmd/checkconfig -- --config-path=/home/prow/go/src/github.com/GoogleCloudPlatform/oss-test-infra/prow/config.yaml

periodics:
# test jobs, remove later
- name: cluster-unspecified
  # cluster:
  interval: 30m
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
- name: cluster-default
  cluster: default
  interval: 30m
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
- name: cluster-gcp-guest
  cluster: gcp-guest
  interval: 30m
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
